// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhhBUdXMjKXcrupXXa3CeAKakl-CWkbp4',
    appId: '1:642877606526:web:771409d558da663347e62f',
    messagingSenderId: '642877606526',
    projectId: 'synq-d18b1',
    authDomain: 'synq-d18b1.firebaseapp.com',
    storageBucket: 'synq-d18b1.firebasestorage.app',
    measurementId: 'G-FQ24R86DFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEDUNj9FGLzl-U6IW7Pmpd-y64MZGzQw',
    appId: '1:642877606526:android:a3f46571a7128dad47e62f',
    messagingSenderId: '642877606526',
    projectId: 'synq-d18b1',
    storageBucket: 'synq-d18b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGkvlKYuL74PNpjLMEqKNGXqTQKYChrg',
    appId: '1:642877606526:ios:deca48de575055d347e62f',
    messagingSenderId: '642877606526',
    projectId: 'synq-d18b1',
    storageBucket: 'synq-d18b1.firebasestorage.app',
    iosBundleId: 'com.example.synq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGkvlKYuL74PNpjLMEqKNGXqTQKYChrg',
    appId: '1:642877606526:ios:deca48de575055d347e62f',
    messagingSenderId: '642877606526',
    projectId: 'synq-d18b1',
    storageBucket: 'synq-d18b1.firebasestorage.app',
    iosBundleId: 'com.example.synq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhhBUdXMjKXcrupXXa3CeAKakl-CWkbp4',
    appId: '1:642877606526:web:345399d3b464d2cd47e62f',
    messagingSenderId: '642877606526',
    projectId: 'synq-d18b1',
    authDomain: 'synq-d18b1.firebaseapp.com',
    storageBucket: 'synq-d18b1.firebasestorage.app',
    measurementId: 'G-B1CK6LEN7K',
  );
}
